[package]
name = "rusty_rogue"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = "0.20.0"
rand = "0.8.5"
enum-map = "2.6.3"
